FROM ubuntu:18.04


RUN apt update
RUN apt install php7
RUN apt install git
RUN apt install python3 python3-pip
RUN python3 -m pip install scipy numpy imutils opencv-python-headless pynetworktables

RUN git clone https://github.com/ewpratten/riocv-py.git ./

RUN php -S 0.0.0.0:2081 & python3 vision.py -c 99